name       : haskell-mmorph
version    : 1.1.3
release    : 3
source     :
    - https://hackage.haskell.org/package/mmorph-1.1.3/mmorph-1.1.3.tar.gz : 7923f7ad6260a05aaa8175b9f2a250f5bb63187427681171bd36d29a6cf2da65
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides monad morphism utilities, most commonly used for manipulating monad transformer stacks.
description: |
    This library provides monad morphism utilities, most commonly used for manipulating monad transformer stacks.
builddeps  :
    - haskell-cabal-install
    - haskell-transformers-compat-devel
rundeps    :
    - devel:
        - haskell-transformers-compat-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
