name       : haskell-mmorph
version    : 1.1.2
release    : 2
source     :
    - https://hackage.haskell.org/package/mmorph-1.1.2/mmorph-1.1.2.tar.gz : c90afd7996c94be2b9a5796a7b94918d198c53b0c1d7a3eaf2982293560c5fbe
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library provides monad morphism utilities, most commonly used for manipulating monad transformer stacks.
description: |
    This library provides monad morphism utilities, most commonly used for manipulating monad transformer stacks.
builddeps  :
    - haskell-cabal-install
    - haskell-mtl
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
